version: "3"

services:
  redis:
    image: redis
    container_name: Wanted_redis
    ports:
      - 6379:6379
  db:
    image: mariadb:10
    container_name: Wanted_mysql
    ports:
      - 3306:3306
    volumes:
      - ./wantedDB/conf.d:/etc/mysql/conf.d
      - ./wantedDB/data:/var/lib/mysql
      - ./wantedDB/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - Wanted
    restart: always

networks:
  Wanted: